name: tolan2024
url: projects/meta-forest-monitoring-okw37/assets/CanopyHeight

gee_project: "ee-thomasboudras04"

root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data
data_dir: ${root_dir}/sota/${name}
gdf_path : ${root_dir}/logs/pred_sera/h-sera_h_max/test_lidarhd/predictions/predict_gdf.geojson
grouping_dates: lidar_acquisition_date
selected_bands: [cover_code]
pixel_range: [0, 255]
min_year: null
max_year: null
split: test


n_jobs_parrallelized : 5

resolution : 1
tile_shape : 5000
max_tile_size : 10
country : "France"
composite_method : MEAN


hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs
  


