dates :
  - "2021/02/15"
  - "2022/02/15"
  # - "2023/02/15" 
  # - "2024/02/15"
  - "2025/02/15"

data_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/sentinel/timeseries/ciaran
# gee_project: "ee-thomasboudras04"
gee_project: "tree-443110"


#Bretagne
bbox:
  left : 78446
  bottom : 6663540
  right : 360010
  top : 6903883

resolution : 10
tile_shape : 5000
max_tile_size : 10
cloudless_portion : 60
cloud_prb : 40
country : "France"
composite_method_s1 : TIMESERIES
composite_method_s2 : TIMESERIES
duration : 100
s1_orbit: BOTH

hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs
