root_dir: /lustre/fsn1/projects/rech/ego/uof45xi/data/
data_dir: ${root_dir}/sentinel/timeseries/diff/
gdf_path : ${root_dir}/utils/gdf_diff_map_initial.geojson
gee_project: "ee-thomasboudras04"

grouping_dates: lidar_acquisition_date_t1

n_jobs_parrallelized : 5

resolution : 10
tile_shape : 5000
max_tile_size : 10
cloudless_portion : 60
cloud_prb : 40
country : "France"
composite_method_s1 : TIMESERIES
composite_method_s2 : TIMESERIES
duration : 60
s1_orbit : BOTH


hydra:
  run :
    dir : ${data_dir}/logs
  output_subdir : hydra_logs
  


