# @package _global_

defaults:
  - override /train: d-sera_d_gc_loss
  - _self_

project : "pred_sera"
run_version: test_diff_map

ckpt_path : ${data_dir}/logs/train_sera/d-sera_d_gc_loss/v4_d-sera_d_gc_loss/best_checkpoints/epoch_070.ckpt
load_just_weights: True

save_dir: ${log_dir}/predictions

via_bounds : null
via_geojson :
  path : ${data_dir}/sentinel/timeseries/diff_map/gdf_diff_map_timeseries_predict.geojson
  split: test

datamodule:
  instance:
    normalization_save_path: ${data_dir}/normalization/sentinel_diff
  dataset:
    get_inputs_t1: 
      open_even_oob: True
    get_inputs_t2: 
      open_even_oob: True


model:
  instance:
    train_metrics: null
    val_metrics: null 
    test_metrics: null
    predictions_save_dir : ${save_dir}
    