# @package _global_

defaults:
  - override /train: h-sera_h_max
  - _self_

project : "pred_sera"
run_name : diff_h-sera_h_max
run_version: test_diff_map
time_type : t1

ckpt_path : ${data_dir}/logs/train_sera/h-sera_h_max/v1_h-sera_h_max/best_checkpoints/epoch_031.ckpt
load_just_weights: True

save_dir: ${log_dir}/predictions_${time_type}

via_bounds : null
via_geojson :
  path : ${data_dir}/sentinel/timeseries/diff_map/predict_gdf_diff_h_max_debug.geojson
  split: test

datamodule:
  dataset:
    predict_dataset: 
      get_inputs: 
        open_even_oob: True
        inputs_path: ${data_dir}/sentinel/timeseries/diff_map/
        vrts_column: valid_vrts_${time_type}
        date_column: lidar_acquisition_date_${time_type}

model:
  instance:
    train_metrics: null
    val_metrics: null 
    test_metrics: null
    predictions_save_dir : ${save_dir}    
